create table public.monthly_analytics (
  id bigint generated by default as identity primary key,
  month text not null unique,
  visitors integer not null default 0,
  pageviews integer not null default 0,
  created_at timestamptz default now()
);